SRC += evaluator/affinetransform.ml evaluator/affinetransform.mli
SRC += evaluator/blendmode.ml evaluator/blendmode.mli
SRC += evaluator/cache.ml evaluator/cache.mli
SRC += evaluator/color.ml evaluator/color.mli
SRC += evaluator/coreimage.ml evaluator/coreimage.mli
SRC += evaluator/delta.ml evaluator/delta.mli
SRC += evaluator/evaluator.ml evaluator/evaluator.mli
SRC += evaluator/expr.ml evaluator/expr.mli
SRC += evaluator/image.ml evaluator/image.mli
SRC += evaluator/interval.ml evaluator/interval.mli
SRC += evaluator/log.ml
SRC += evaluator/marray.ml evaluator/marray.mli
SRC += evaluator/mlist.ml evaluator/mlist.mli
SRC += evaluator/optevaluator.ml evaluator/optevaluator.mli
SRC += evaluator/optimiser.ml evaluator/optimiser.mli
SRC += evaluator/point.ml evaluator/point.mli
SRC += evaluator/primitives.ml evaluator/primitives.mli
SRC += evaluator/printer.ml evaluator/printer.mli
SRC += evaluator/rect.ml evaluator/rect.mli
SRC += evaluator/registerer.ml
SRC += evaluator/size.ml evaluator/size.mli
SRC += evaluator/type.ml evaluator/type.mli
SRC += evaluator/typechecker.ml evaluator/typechecker.mli
